create or replace TABLE QUA_EMEA.BROZ.COMMANDE (
	SALESORDERID NUMBER(38,0),
	REVISIONNUMBER NUMBER(38,0),
	ORDERDATE TIMESTAMP_NTZ(9),
	DUEDATE TIMESTAMP_NTZ(9),
	SHIPDATE TIMESTAMP_NTZ(9),
	STATUS NUMBER(38,0),
	SALESORDERNUMBER VARCHAR(25),
	PURCHASEORDERNUMBER VARCHAR(25),
	CUSTOMERID NUMBER(38,0),
	SALESPERSONID NUMBER(38,0),
	TERRITORYID NUMBER(38,0),
	BILLTOADDRESSID NUMBER(38,0),
	SHIPTOADDRESSID NUMBER(38,0),
	SHIPMETHODID NUMBER(38,0),
	CREDITCARDID NUMBER(38,0),
	COMMENT VARCHAR(128),
	MODIFIEDDATE TIMESTAMP_NTZ(9)
);
