create or replace TABLE BROZ."0GL_ACCOUNT_TEXT" (
	LANGU VARCHAR(1),
	KEY1 VARCHAR(60),
	KEY2 VARCHAR(32),
	DATETO DATE,
	DATEFROM DATE,
	TXTSH VARCHAR(20),
	TXTMD VARCHAR(40),
	TXTLG VARCHAR(60)
);

