create or replace TABLE SAPBW_0BILL_BLOCK_TEXT (
	"0BILL_BLOCK" VARCHAR(2) NOT NULL,
	"0LANGU" VARCHAR(1) NOT NULL,
	"0TXTSH" VARCHAR(20),
	constraint "pk_DEV_EMEA_BROZ_SAPBW_0BILL_BLOCK_TEXT" primary key ("0BILL_BLOCK", "0LANGU")
);